### ISSUE TITLE
security issue: Spark can Run SQL on files directly

### ISSUE THREAD

**Issue by brucemen711** [yaooqinn/spark-ranger#12]
Currenlly, Spark can Run SQL on files directly, for example:
val sqlDF = spark.sql("SELECT * FROM parquet.`examples/src/main/resources/users.parquet`")

It make some other user can explore data directly from files.
What do you think @yaooqinn  ?

**Comment by yaooqinn** [comment]
use ranger hdfs plugin

**Comment by brucemen711** [comment]
But is any conflig between parquet hive table (user table) and hdfs parquet file (user parquet file) if i set diff policy ?

**Comment by brucemen711** [comment]
I want custom filter to prevent user do that, any suggestion which class to look for ?

**Comment by yaooqinn** [comment]
I am not very sure, you can look up the logical plan to see if any pattern you can match to prohibit such behavior

**Comment by brucemen711** [comment]
> I am not very sure, you can look up the logical plan to see if any pattern you can match to prohibit such behavior

ok, i will give a try.
Thanks

**Comment by brucemen711** [comment]
Closed issue as it doesnt relate to this plugin.
Thanks.
