### ISSUE TITLE
sparkPlugin init too many times

### ISSUE THREAD

**Issue by brucemen711** [yaooqinn/spark-ranger#14]
Hi @yaooqinn ,

I see sparkPlugin  init so many times on class RangerSparkMaskingExtension and RangerSparkRowFilterExtension.
is any reason for that ? Can we make sparkPlugin  static ?

**Comment by yaooqinn** [comment]
Do you mean the current implementation will not reuse the sparkPlugin？

**Comment by brucemen711** [comment]
T try using query(select), RangerSparkRowFilterExtension always invoke so sparkPlugin is inited everytime query happen.

**Comment by yaooqinn** [comment]
As this project is moved to Apache Submarine as a submodule, I'll make a pr to resolve this there.

**Comment by brucemen711** [comment]
Ok, thanks for your info.

**Comment by brucemen711** [comment]
I will close it now, thanks you.
