### ISSUE TITLE
查询语句分区过滤不起作用，进行全表扫描

### ISSUE THREAD

**Issue by liu372943162** [yaooqinn/spark-ranger#24]
我们使用 ranger1.0，spark2.4，在配置好后，权限可以对spark-thrift 生效，但是查询sql 不会优先使用分区条件进行筛选，而是直接进行全表扫描，导致查询很慢，不知道这个问题有没有朋友遇到过

**Comment by yaooqinn** [comment]
Hi @liu372943162 
It duplicates https://github.com/yaooqinn/spark-ranger/issues/17, please check existing issues before opening an issue, thanks

**Comment by liu372943162** [comment]
对不起，对github还不是很熟悉，下午没有注意到看到已关闭的问题标签页，带来不便，实在抱歉
作者您这个功能写的很棒，填补了空白，感谢开源。
