### ISSUE TITLE
ranger 2.0 support

### ISSUE THREAD

**Issue by PedroRossi** [yaooqinn/spark-ranger#4]
I noticed that the project README only list 1.0, 1.1 and 1.2 ranger versions as profiles available, but the project pom shows ranger 2.0 also, the only issue with it is that the `RangerAdminClientImpl` needs to change from `extends RangerAdminClient` to `extends AbstractRangerAdminClient` in order to work.

I am creating this issue so I can address it on a PR latter.

**Comment by brucemen711** [comment]
Hi PedroRossi, 
We are using ranger 2.0, so im looking for your PR.
Thanks.

**Comment by yaooqinn** [comment]
thanks for reporting this, feel free to make pr , thanks
